# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: indietech.rocks
description: > # this means to ignore newlines until "baseurl:"
  Finding products that don't screw us. Open source. Privacy. FLOSS. GPL. Apache. Open hardware.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://indietech.rocks" # the base hostname & protocol for your site

exclude: [ 'bin' ]
future: false

twitter_username: indietechrocks
github_username: indietechrocks
facebook_username: indietechrocks

# Build settings
markdown: kramdown

theme: jekyll-theme-architect

